blogg/blog/urls.py
from django.urls import path

from .views import all_posts_view,category_view,tag_view,post_detail_view

app_name = "blog"
urlpatterns = [
    path("",all_posts_view,name="all_posts_view"),
    path("category/<slug:category_slug>/",category_view,name="category_view"),
    path("category/<slug:category_slug>/<slug:post_slug>/",post_detail_view,name="post_detail_view"),
    
    path("tag/<slug:tag_slug>/",tag_view,name="tag_view"),
]

blogg/config/urls.py
from django.contrib import admin
from django.urls import path,include

from page.views import home_view
from config.views import logout_view


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',home_view,name='home'),

    path("page/",include("page.urls",namespace="page")),

    path("todo/",include("todo.urls",namespace = "todo")),

    path("blog/",include("blog.urls",namespace = "blog")),

    path("account/logout", logout_view, name="logout_view"),

    path("tinymce/",include("tinymce.urls")),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogg/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="tr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title%}{% endblock title%}Django Firma Demo</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body>
    {% include 'core/navbar.html' %}
    {% block container-fluid %}
    {% endblock container-fluid %}
    <div class="mt-4">

    <div class="container">
    {% block container %}
    {% endblock container %}
    </div>
    {# PROJELER INCLUDE ile EKLENDI #}
    {% include 'core/projects.html' %}
    </div>


    {% include 'core/footer.html' %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

blogg/templates/core/footer.html
<!-- FOOTER -->
<div class="bg-dark text-light mt-5">
    <div class="container">
        <footer class="pt-5">
            <div class="row">
                <div class="col-6 col-md-2 mb-3">
                    <h5>Section</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                    </ul>
                </div>

                <div class="col-6 col-md-2 mb-3">
                    <h5>Section</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                    </ul>
                </div>

                <div class="col-6 col-md-2 mb-3">
                    <h5>Section</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                    </ul>
                </div>

                <div class="col-md-5 offset-md-1 mb-3">
                    <form>
                        <h5>Subscribe to our newsletter</h5>
                        <p>Monthly digest of what's new and exciting from us.</p>
                        <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                            <label for="newsletter1" class="visually-hidden">Email address</label>
                            <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                            <button class="btn btn-primary" type="button">Subscribe</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="d-flex flex-column flex-sm-row justify-content-between py-4 border-top">
                <p>© 2022 Company, Inc. All rights reserved.</p>
                <ul class="list-unstyled d-flex">
                    <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24">
                                <use xlink:href="#twitter"></use>
                            </svg></a></li>
                    <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24">
                                <use xlink:href="#instagram"></use>
                            </svg></a></li>
                    <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24">
                                <use xlink:href="#facebook"></use>
                            </svg></a></li>
                </ul>
            </div>
        </footer>
    </div>
</div>
<!-- FOOTER END -->

blogg/templates/core/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="/">DjangoMania</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">Ana sayfa</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Todo Kategoriler
              </a>
              <ul class="dropdown-menu">
                {% for category in global_todo_categories %}
                    <li class="nav-item">
                        <a style="color: black;" class="nav-link" href="{{ todo.get_absolute_url }}">{{ category.title }}</a>
                    </li>
                {% endfor %}
              </ul>
            </li>
            {% for page in global_pages %}
            <li class="nav-item"><a class="nav-link" href="{{ page.get_absolute_url }}">{{ page.title }}</a></li>   
            {% endfor %}
            <li class="nav-item"><a class="nav-link" href="{% url 'blog:all_posts_view' %}">Blog</a></li>
            {% if request.user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'logout_view' %}">Oturumu Kapat</a></li>
            {% endif %}
        </ul>
      </div>
    </div>
  </nav>

blogg/templates/core/projects.html
<!-- Projects -->
<div class="row my-4">
    <!-- .col-sm*8>img.w-100[src="https://picsum.photos/id/2$/100/80"] -->
    <div class="col-sm-12">
        <h2>Projelerimiz</h2>
        <hr>
    </div>

    {% for item in FAKE_DB_PROJECTS %}
        <div class="col-sm col-6 mb-1">
            <img src="{{ item }}" alt="" class="w-100 img-thumbnail">
        </div>
    {% empty %}
        <h3 class="text-danger">Proje Bulunamadi..</h3>
    {% endfor %}   
</div>
<!-- Projects END -->